# NumPy

Para instalar Numpy:  
-desde Anaconda: conda install numpy  
-cmd: pip install numpy  

Numpy para trabajar con arrays, matrices, vectores

In [6]:
import numpy as np

In [8]:
#creamos un array a partir de una lista
lista = [1,2,3,4,5,6]

In [14]:
array = np.array(lista)
array

array([1, 2, 3, 4, 5, 6])

In [16]:
#matriz
lista2 = [[1,2,3],[4,5,6],[7,8,9]]
lista2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
array2=np.array(lista2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Numpy arrays - arange, zeros, ones, linspace, eye

In [30]:
import numpy as np
array = np.arange(5)  #genera un array de 5 eltos que empieza en 0

In [32]:
array

array([0, 1, 2, 3, 4])

In [44]:
np.arange(1,20,3)  #(inicio,final, paso)

array([ 1,  4,  7, 10, 13, 16, 19])

In [50]:
#zeros: genera una matriz o un array de la forma

np.zeros((3,4)) genera una matriz de filasxcolumnas con todos los eltos de valor 0, si ponemos solo un numero será una fila

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
np.ones((3,4))  #lo mismo pero con ones, unos

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
#linspace
np.linspace(5,8,10)  #genera una matriz con el primer elto, y ultimo elto y 50 es el número de eltos generado

array([5.        , 5.33333333, 5.66666667, 6.        , 6.33333333,
       6.66666667, 7.        , 7.33333333, 7.66666667, 8.        ])

In [60]:
#eye - genera una matriz cuadrada
np.eye(5)  #genera una matriz de 5x5, con todos los eltos 0 menos la diagonal principal que es a 1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Numpy arrays - números aleatorios - rand, randn, randint

In [67]:
import numpy as np

In [69]:
np.random.rand(5)  #array de una fila aleatorio de 5 eltos

array([0.40361325, 0.94628834, 0.74992836, 0.14512086, 0.5427122 ])

In [73]:
np.random.rand(2,5)

array([[0.18125858, 0.60182427, 0.4641686 , 0.51164834, 0.54311819],
       [0.36238735, 0.28517607, 0.65266046, 0.69953047, 0.08675788]])

In [75]:
np.random.randn(5)  #genera numeros normales, incluidos negativos Return a sample (or samples) from the "standard normal" distribution.

array([ 2.39093202,  0.11677019, -1.57410147, -1.61376556,  0.33357678])

In [87]:
np.random.randint(1,6)  #genera un número entero aletario entre los rangos que le damos

5

In [91]:
np.random.randint(1,10,5)

array([4, 4, 9, 5, 3])

### Numpy arrays - reshape, max, min

In [99]:
array = np.random.randint(1,100,25)
array

array([11, 84, 96, 36, 68, 78, 46, 72, 27, 74,  9,  7, 93, 19, 29, 89, 89,
       81, 66,  5, 53, 33, 72, 15, 32])

In [111]:
#para transformar este array en una matriz, para cambiar el formato de las matrices tambien
matriz = array.reshape(5,5)  #siempre que el filasxcolumnas sea igual al numero de eltos que teniamos 5x5=25 para que entren todos
matriz

array([[11, 84, 96, 36, 68],
       [78, 46, 72, 27, 74],
       [ 9,  7, 93, 19, 29],
       [89, 89, 81, 66,  5],
       [53, 33, 72, 15, 32]])

In [128]:
valor_maximo = array.max()
posicion_valor_maximo = array.argmax()
print("El valor maximo es {} que está en la posicion {}".format(valor_maximo, posicion_valor_maximo))

El valor maximo es 96 que está en la posicion 2


In [124]:
valor_min= array.min()
posicion_valor_min =array.argmin()
print("El valor mínimo es {} que está en la posicion {}".format(valor_min, posicion_valor_min))

El valor mínimo es 5 que está en la posicion 19


### Indexación en los arrays

In [138]:
array[19]

5

In [140]:
#ultimo elto del array
array[-1]

32

In [142]:
array[:]  #todo el array
array[5:] #desde la posicion 5 hasta el final
array[:4] #hasta la posicion 4 (sin incluirla)

array([11, 84, 96, 36, 68, 78, 46, 72, 27, 74,  9,  7, 93, 19, 29, 89, 89,
       81, 66,  5, 53, 33, 72, 15, 32])

In [146]:
#copia de un array
array2= array.copy()
array2


array([11, 84, 96, 36, 68, 78, 46, 72, 27, 74,  9,  7, 93, 19, 29, 89, 89,
       81, 66,  5, 53, 33, 72, 15, 32])

In [148]:
#para dos dimensiones, como matriz
matriz

array([[11, 84, 96, 36, 68],
       [78, 46, 72, 27, 74],
       [ 9,  7, 93, 19, 29],
       [89, 89, 81, 66,  5],
       [53, 33, 72, 15, 32]])

In [154]:
matriz[0][3] #[fila][columna] tambien vale con coma [fila,columna]

36

In [156]:
matriz[0,3]

36

In [152]:
#seleccionar una fila
matriz[2]

array([ 9,  7, 93, 19, 29])

In [158]:
matriz[:,0]  #para localizar una unica columna, primero le decimos que todas las filas, y luego qué columna 

array([11, 78,  9, 89, 53])

In [164]:
matriz[:,-1]  #ultima columna

array([68, 74, 29,  5, 32])

### Seleccionar eltos de un array según una condición

In [175]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [177]:
condicion = array >5
condicion  #nos da booleanos de false o true para ver si se cumple la condición

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [183]:
array[condicion]  #los que la condición es true

array([6, 7, 8, 9])

In [191]:
array_pares = array[array%2==0]
array_pares

array([0, 2, 4, 6, 8])

### Operaciones sobre los arrays

In [217]:
operacion = array + array *100
operacion

array([  0, 101, 202, 303, 404, 505, 606, 707, 808, 909])

In [211]:
#func  sobre los array. escribe np. y pulsa tab y verás las func a poder utilizar
np.square(array)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [219]:
np.max(operacion)

909

---

In [ ]:
#Ejercicios


In [ ]:
#Crea una lista de num secuencias, con min 10 y max 39
#convierte esta en lista en matris de 3x10
#muestra el valor del elto de la esquina superior derecha de la matriz

In [236]:
import numpy as np
lista = np.arange(10,40)
lista =lista.reshape(3,10)
lista

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [238]:
lista[0,9]

19

In [240]:
#Crea un array de 1 dimension con 9 valores enteros aleatorios entre 0 y 100
#convierte el array en matriz de 3x3
#muestra en pantalla el valor esquina inferior derecha

In [257]:
import numpy as np
lista = np.random.randint(0,100,9)
print(lista)
lista = lista.reshape(3,3)
print(lista)
print(lista[2][2])

[27 54  9 97 96 55 64 84 12]
[[27 54  9]
 [97 96 55]
 [64 84 12]]
12


In [261]:
def fun(N, min, max):
    return np.random.randint(min, max, N)

N=5
min= 1
max = 10

resultado = fun(N,min, max)
print(resultado)

[4 9 7 6 1]


'''Desarrolla una función llamada generar_numeros_enteros_aleatorios
que tome como entrada el número de elementos N, un valor mínimo minimo y un valor máximo maximo, 
y utilice NumPy para generar una lista de N números enteros aleatorios en el rango [minimo, maximo].
SUGERENCIA: Utiliza la función tolist() para convertir la salida de randint() en una lista
'''

In [265]:
import numpy as np
def generar_numeros_enteros_aletarios(N,minimo, maximo):
    return np.random.randint(minimo, maximo + 1, size=N).tolist()

# Ejemplo de uso
N = 5
minimo = 1
maximo = 10
resultado = generar_numeros_enteros_aletarios(N, minimo, maximo)
print(resultado)


[10, 2, 6, 10, 2]


'''
Desarrolla una función llamada generar_secuencia_numerica 
que tome como entrada un valor mínimo minimo, un valor máximo maximo y un paso paso, 
utilice NumPy para generar una secuencia de números en el rango [minimo, maximo) con el paso especificado.

'''

In [271]:
import numpy as np
def generar_secuencia_numerica(minimo, maximo, paso):
    return np.arange(minimo, maximo, paso).tolist()
# Ejemplo de uso
minimo = 0
maximo = 10
paso = 2
resultado = generar_secuencia_numerica(minimo, maximo, paso)
print(resultado)

[0, 2, 4, 6, 8]
